# Generated by Django 5.1.5 on 2025-01-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom_client', models.CharField(max_length=50)),
                ('tele_client', models.CharField(max_length=15)),
                ('email_client', models.EmailField(max_length=254)),
                ('adress_client', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=50)),
                ('adress_fournisseur', models.CharField(max_length=50)),
                ('tele_fournisseur', models.CharField(max_length=15)),
                ('email_fournisseur', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date_commande', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='inventory.client')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=3, max_digits=15)),
                ('quantite_stock', models.PositiveIntegerField()),
                ('date_exp', models.DateField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='inventory.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.commande')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicament')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='medicament',
            field=models.ManyToManyField(through='inventory.CommandeDetail', to='inventory.medicament'),
        ),
    ]
